export const catActionTypes = {
    SET_VOTES: "SET_VOTES",
    FETCH_VOTES_ERROR: "FETCH_VOTES_ERROR",
    CREATE_VOTE: "CREATE_VOTE",
    REMOVE_VOTE: "REMOVE_VOTE",
    SET_SPECIFIC_VOTE: "SET_SPECIFIC_VOTE",
    SET_LOADING: "SET_LOADING",
}

export const uiActionTypes = {
    SET_NAVBAR_VISIBILITY: "SET_NAVBAR_VISIBILITY",
}
